### ISSUE TITLE
!Top command prints out in ascending, not descending order in QuizEngine

### ISSUE THREAD

**Issue by Thorpy** [Sovietmade/TwitchChatBot#1]
I understand this is an old project, but hopefully people might find this issue helpful, sorry it's not a commit but I don't have Git Bash installed

Issue: The "Top" command would print out the lowest scores first, meaning if 15 people had played, you'd have to use "!Top15" in order to see the person with the highest score. P.S There is also a !Top5 function which never gets called, as the "!Top(X)" function also allows for !Top5 to be used, so it doesn't need to be there.

Fixed function below (changes made: mScoreList.OrderBy**Descending**):

`
void TopX(int inX)
        {
            string score;
            var result = mScoreList.OrderByDescending(p => p.Score).Where((p, i) => i < inX).Select(p => p.ToString());
            score = String.Join(" ", result);

            SendMessage(score);
        }
`

**Comment by Sovietmade** [comment]
hey, man!
thanks for your interest in improving the project. your changes has been applied. im going to get back to developing and supporting this project soon, i hope. cheers
